### ISSUE TITLE
Include .babelrc example in babel-plugin-transform-try-await readme

### ISSUE THREAD

**Issue by Jarred-Sumner** [fouad/proposal-try-expressions#1]
[babel-plugin-transform-try-await](https://github.com/fouad/proposal-try-expressions/blob/master/packages/babel-plugin-transform-try-await/readme.md)'s readme doesn't include an example of what to paste into your `.babelrc` to make use of this as a babel plugin.

It would make it easier to get started if it included an example `.babelrc` file pasted into the readme to explain how to add it to a repo.

e.g.

### Configuration

To get started, add this package to your babel configuration.

To do that, add `"module:babel-plugin-transform-try-await"` to `"plugins"` within your babel configuration.

Example `.babelrc` file:
```javascript
{
  "plugins": ["module:babel-plugin-transform-try-await"]
}
```

**Comment by fouad** [comment]
thanks for pointing out! still need to implement the plugin and will add to README after that
